# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  version: '0.0.1'

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '8.x'

- script: npm install
  displayName: 'Install npm'

- script: npm install -g vsce
  displayName: 'Install vsce'

- script: npm install -g json
  displayName: 'Install vsce'

- script: json -I -f package.json -e 'this.version="$(version)"'
  displayName: 'Update version'

- script: vsce package
  displayName: 'Generate .vsix'

- task: CopyFiles@2
  inputs:
    contents: '**/*.vsix'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: vscode-inf
     
